# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3991fc1bbe8ece0ae10e545f1e3f0091ff3f4131d35dd32cacc0f2ae364c55603dc148c096bd785f537d7a4cc7092c27ee9c16664d13f3c4cb829d077d188343

test:
  secret_key_base: e6571ab3d5fd05474cf1c949ff3b04768674615525da53fb60056040e354219db74610cc04a8dae916d1fca02de5370048cfc53b15266d34ebfa4ccd185c3afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
